import { test, expect } from '@playwright/test';
import { fixture } from './fixture';
import { consoleInput } from './console-helpers';

test('native agent rows preview, render live metadata and rules, cancel, persist, and preserve terminal identity', async ({ page }) => {
  const runtime = await fixture();
  try {
    const active = JSON.parse(await runtime.cli('workspace', 'create')).result.root_pane;
    const background = JSON.parse(await runtime.cli('workspace', 'create')).result.root_pane;
    const other = JSON.parse(await runtime.cli('workspace', 'create')).result.root_pane;
    await runtime.cli('workspace', 'rename', background.workspace_id, 'Mercury research');
    await runtime.cli('pane', 'report-agent', background.pane_id, '--source', 'row-agent', '--agent', 'Claude', '--state', 'blocked', '--seq', '1');
    await runtime.cli('pane', 'report-agent', other.pane_id, '--source', 'other-agent', '--agent', 'Codex', '--state', 'working', '--seq', '1');
    const metadata = (...args: string[]) => runtime.cli('pane', 'report-metadata', background.pane_id, '--source', 'row-metadata', '--agent', 'Claude', '--applies-to-source', 'row-agent', ...args);
    await metadata('--display-agent', 'Researcher', '--title', 'Review findings', '--state-label', 'blocked=needs approval', '--token', 'load=90', '--token', 'summary=<b>literal metadata</b>', '--seq', '1');
    await page.goto(runtime.url + `/?machine=local&workspace=${active.workspace_id}&tab=${encodeURIComponent(active.tab_id)}&pane=${encodeURIComponent(active.pane_id)}`);
    await consoleInput(page, 'token', runtime.token); await expect(page.locator('#shield')).toBeHidden();
    const terminal = await page.locator('#terminal textarea').elementHandle();
    const row = page.locator(`#agents button[data-id="local/${background.pane_id}"]`);
    await expect(row.locator('.agent-line')).toHaveCount(2);
    await expect(row.locator('[data-token=workspace]')).toHaveText('Mercury research');
    await expect(row.locator('[data-token=agent]')).toHaveText('Researcher');
    const identity = await row.elementHandle();
    await page.screenshot({ path: 'test-results/agent-rows-default-desktop.png' });
    await page.locator('#settings').click(); await page.locator('#settings-agent-rows summary').click();
    const editor = page.locator('#settings-agent-row-config');
    const config = { rows: [['state_icon']], rows_by_agent: { claude: [['state_icon', 'workspace'], ['agent', 'state_text'], ['pane'], ['$summary'], [{ token: '$load', fg: '#abc', bold: true, rules: [{ gt: 80, fg: '#f44', bold: false, dim: false }] }], ['$missing']] }, row_gap: 1 };
    await editor.fill(JSON.stringify(config));
    await expect(row.locator('.agent-line')).toHaveCount(5);
    await expect(page.locator(`#agents button[data-id="local/${other.pane_id}"] .agent-line`)).toHaveCount(1);
    const spacing = await row.evaluate(node => ({ gap: parseFloat(getComputedStyle(node).marginBottom), line: node.querySelector('.agent-line')!.getBoundingClientRect().height }));
    expect(Math.abs(spacing.gap - spacing.line), JSON.stringify(spacing)).toBeLessThan(1);
    await expect(row.locator('[data-token=state_text]')).toHaveText('needs approval');
    await expect(row.locator('[data-token=custom]').first()).toHaveText('<b>literal metadata</b>');
    await expect(row.locator('b')).toHaveCount(0);
    const load = row.locator('[data-token=custom]').last();
    await expect(load).toHaveCSS('color', 'rgb(255, 68, 68)'); await expect(load).toHaveCSS('font-weight', '400'); await expect(load).toHaveCSS('opacity', '1');
    await editor.fill('{ invalid'); await expect(page.locator('#settings-error')).toContainText('valid JSON');
    await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click(); await expect(page.locator('#settings-dialog')).toBeVisible();
    await page.locator('#settings-cancel').click(); await expect(row.locator('.agent-line')).toHaveCount(2);
    expect(await identity!.evaluate(node => node === document.querySelector('#agents button'))).toBe(true);
    expect(await terminal!.evaluate(node => node === document.querySelector('#terminal textarea'))).toBe(true);
    await page.locator('#settings').click(); await page.locator('#settings-agent-rows summary').click();
    await editor.fill(JSON.stringify(config)); await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click();
    await expect(page.locator('#settings-dialog')).toBeHidden();
    await metadata('--token', 'load=30', '--seq', '2');
    await expect(load).toHaveText('30'); await expect(load).toHaveCSS('color', 'rgb(170, 187, 204)'); await expect(load).toHaveCSS('font-weight', '700');
    await page.screenshot({ path: 'test-results/agent-rows-custom-desktop.png' });
    await runtime.restartGateway(); await page.reload(); await expect(page.locator('#shield')).toBeHidden();
    await expect(row.locator('.agent-line')).toHaveCount(5); await expect(load).toHaveText('30');
    const stored = await (await page.request.get(runtime.url + '/api/settings')).json(); expect(stored.preferences.agentRows).toEqual(config);
    // Saving the same dialog after another browser changes settings must not overwrite that browser.
    await page.locator('#settings').click();
    const response = await page.request.post(runtime.url + '/api/settings', { headers: { Origin: runtime.url }, data: { revision: stored.revision, preferences: { ...stored.preferences, theme: 'nord' } } }); expect(response.ok()).toBe(true);
    await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click(); await expect(page.locator('#settings-error')).toContainText('another browser');
    await page.locator('#settings-cancel').click();
    await page.locator('#settings').click(); await page.locator('[data-setting=sidebarWidth]').fill('160');
    await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click();
    await expect(page.locator('#settings-dialog')).toBeHidden();
    await expect(row).toBeVisible();
    const withinRows = () => row.locator('.agent-line').evaluateAll(lines => lines.every(line => [...line.querySelectorAll<HTMLElement>('.agent-token:not([hidden])')].every(token => token.getBoundingClientRect().right <= line.getBoundingClientRect().right + 1)));
    await expect.poll(withinRows).toBe(true);
    await page.screenshot({ path: 'test-results/agent-rows-narrow-desktop.png' });
    await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#host-toggle').click();
    await expect(row).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/agent-rows-mobile.png' });
    await row.click(); await expect(page).toHaveURL(new RegExp(`pane=${encodeURIComponent(background.pane_id)}`));
  } finally { await runtime.close(); }
});
