import { test, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fixture } from './fixture';
import { consoleInput } from './console-helpers';

let runtime: Awaited<ReturnType<typeof fixture>>;
test.beforeAll(async () => { runtime = await fixture(); });
test.afterAll(async () => { await runtime?.close(); });

test('background agent activity, native rename, saved selection, host management and notifications survive reconnect', async ({ page }) => {
  const first = JSON.parse(await runtime.cli('workspace', 'create')).result.root_pane;
  const second = JSON.parse(await runtime.cli('workspace', 'create')).result.root_pane;
  let sequence = 0;
  const report = (state: string) => runtime.cli('pane', 'report-agent', second.pane_id, '--source', 'werdr-fleet-test', '--agent', 'Claude', '--state', state, '--seq', String(++sequence));
  await report('working');
  await page.goto(runtime.url + `/?machine=local&workspace=${first.workspace_id}&tab=${first.tab_id}&pane=${first.pane_id}`);
  await consoleInput(page, 'token', runtime.token);
  await expect(page.locator('#boot')).toBeHidden();
  await expect(page.locator('#shield')).toBeHidden();
  await expect(page.locator('#agents button')).toHaveCount(1);
  await expect(page.locator('#agents button')).toHaveAttribute('data-badge', 'WORKING');
  await report('blocked');
  await expect(page.locator('#agents button')).toHaveAttribute('data-badge', 'BLOCKED');
  await expect(page.locator('#activity')).toContainText('[1]');
  await page.locator('#activity').click();
  await expect(page.locator('#notice-list .notice-row')).toHaveCount(1);
  await page.getByRole('button', { name: 'OPEN PANE', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`pane=${encodeURIComponent(second.pane_id)}`));
  await expect(page.locator('#shield')).toBeHidden();
  await page.keyboard.press('Control+k');
  await page.locator('#command-search').fill('Rename workspace');
  await page.locator('#command-list button').click();
  await page.locator('#rename-value').fill('Fleet review');
  await page.locator('#rename-form button[type=submit]').click();
  await expect(page.locator('#workspaces')).toContainText('Fleet review');
  await page.reload();
  await expect(page.locator('#boot')).toBeHidden();
  await expect(page.locator('#shield')).toBeHidden();
  await expect(page.locator('#panes button.active')).toHaveAttribute('data-id', second.pane_id);
  await page.locator('#workspaces button').first().click();
  await report('idle');
  await expect(page.locator('#activity')).toContainText('[1]');
  await page.locator('#activity').click();
  await expect(page.locator('#notice-list .notice-row')).toHaveCount(2);
  await page.locator('#read-notices').click();
  await expect(page.locator('#notice-list .notice-row[data-read=false]')).toHaveCount(0);
  await page.locator('#activity-done').click();
  const catalogDir = join(runtime.directory, 'state/herdr/client');
  await mkdir(catalogDir, { recursive: true });
  const offline = { id: 'a'.repeat(32), label: 'Offline fixture', target: '127.0.0.1', session: 'unavailable', enabled: false };
  await writeFile(join(catalogDir, 'endpoints.json'), JSON.stringify({ version: 1, ssh: [offline] }), { mode: 0o600 });
  await expect(page.locator('#hosts button')).toHaveCount(2);
  await page.locator('#manage-hosts').click();
  await expect(page.locator('#host-manager')).toBeVisible();
  await page.screenshot({ path: 'test-results/fleet-hosts-desktop.png' });
  let row = page.locator('.managed-host').filter({ hasText: 'Offline fixture' });
  await row.getByRole('button', { name: 'RENAME', exact: true }).click();
  await page.locator('#host-rename').fill('Renamed fixture');
  await page.getByRole('button', { name: 'SAVE LABEL', exact: true }).click();
  row = page.locator('.managed-host').filter({ hasText: 'Renamed fixture' });
  await expect(row).toBeVisible();
  await row.getByRole('button', { name: 'ENABLE', exact: true }).click();
  await expect(row).toContainText('[OFFLINE]');
  await expect(page.locator('#hosts button').first()).toHaveAttribute('data-badge', 'ONLINE');
  await row.getByRole('button', { name: 'DISABLE', exact: true }).click();
  await expect(row).toContainText('[DISABLED]');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/fleet-hosts-mobile.png' });
  page.once('dialog', dialog => dialog.accept());
  await row.getByRole('button', { name: 'REMOVE', exact: true }).click();
  await expect(page.locator('.managed-host')).toHaveCount(1);
  await page.locator('#host-target').fill('203.0.113.20');
  await expect(page.locator('#host-label')).toHaveValue('203.0.113.20');
  await page.getByRole('button', { name: 'CHECK AND SET UP', exact: true }).click();
  await expect(page.locator('#setup-status')).toContainText('FAILED');
  await expect(page.locator('#setup-output')).toContainText('private LAN');
  await page.locator('#setup-done').click();
  await runtime.restartGateway(); await page.reload();
  await expect(page.locator('#boot')).toBeHidden();
  await expect(page.locator('#shield')).toBeHidden();
  await page.locator('#host-toggle').click();
  await page.locator('#activity').click();
  await expect(page.locator('#notice-list .notice-row')).toHaveCount(2);
  await expect(page.locator('#notice-list .notice-row[data-read=false]')).toHaveCount(0);
});
