import { test, expect } from '@playwright/test';
import { fixture } from './fixture';
import { consoleInput } from './console-helpers';

test('native pane borders, shared dividers and bottom tabs preserve terminal input and copy controls', async ({ page }) => {
  test.setTimeout(90000);
  const runtime = await fixture();
  try {
    await page.goto(runtime.url); await consoleInput(page, 'token', runtime.token); await expect(page.locator('#boot')).toBeHidden();
    await page.getByRole('button', { name: 'Create workspace', exact: true }).click(); await expect(page.locator('#shield')).toBeHidden();
    const first = new URL(page.url()).searchParams.get('pane')!;
    const firstPane = page.locator(`.terminal-pane[data-pane="${first}"]`);
    const original = await firstPane.locator('textarea').elementHandle();
    await expect(firstPane.locator('.pane-title')).toBeHidden();
    await expect(firstPane).toHaveCSS('border-left-width', '0px');
    const run = async (label: string) => { await page.locator('#commands').click(); await page.locator('#command-list').getByRole('button', { name: label, exact: true }).click(); };
    await run('Split right (Ctrl/Cmd+D)'); await expect(page.locator('.terminal-pane:visible')).toHaveCount(2);
    await expect(page.locator('#shield')).toBeHidden();
    const second = new URL(page.url()).searchParams.get('pane')!;
    const secondPane = page.locator(`.terminal-pane[data-pane="${second}"]`);
    await expect(firstPane.locator('.pane-title')).toBeVisible();
    await expect(secondPane).toHaveCSS('border-right-width', '1px');
    await page.locator('#settings').click();
    await page.locator('[data-setting=tabBarPosition]').selectOption('bottom');
    await page.locator('[data-setting=paneOuterBorders]').uncheck();
    await page.locator('[data-setting=paneGaps]').uncheck();
    await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click();
    await expect(page.locator('#settings-dialog')).toBeHidden();
    const terminal = await page.locator('#terminal').boundingBox(), tabs = await page.locator('#tabs').boundingBox();
    expect(tabs!.y).toBeCloseTo(terminal!.y + terminal!.height, 0);
    const left = await firstPane.boundingBox(), right = await secondPane.boundingBox();
    expect(left!.x + left!.width).toBeCloseTo(right!.x, 1);
    await expect(firstPane).toHaveCSS('border-left-width', '0px');
    await expect(firstPane).toHaveCSS('border-right-width', '0px');
    await expect(secondPane).toHaveCSS('border-left-width', '1px');
    await expect(secondPane.locator('.pane-title')).toBeHidden();
    const divider = page.locator('.pane-divider'); const box = await divider.boundingBox();
    await page.mouse.move(box!.x + 2, box!.y + 50); await page.mouse.down(); await page.mouse.move(box!.x + 82, box!.y + 50); await page.mouse.up();
    await expect.poll(async () => (await firstPane.boundingBox())!.width).toBeGreaterThan(left!.width + 50);
    await run('Zoom / restore pane'); await expect(page.locator('.terminal-pane:visible')).toHaveCount(1);
    await expect(secondPane).toHaveCSS('border-left-width', '0px');
    await run('Zoom / restore pane'); await expect(page.locator('.terminal-pane:visible')).toHaveCount(2);
    await page.locator('#settings').click(); await page.locator('[data-setting=paneBorders]').uncheck();
    await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click(); await expect(page.locator('#settings-dialog')).toBeHidden();
    await expect(secondPane).toHaveCSS('border-left-width', '0px');
    const ratio = Number(await divider.getAttribute('aria-valuenow'));
    await divider.focus(); await page.keyboard.press('ArrowLeft');
    await expect(divider).toHaveAttribute('aria-valuenow', String(ratio - 5));
    await secondPane.locator('textarea').focus(); await page.keyboard.type("export CHROME_KEEP=alive; printf 'CHROME_%s\\n' \"$CHROME_KEEP\""); await page.keyboard.press('Enter');
    await expect.poll(() => runtime.cli('pane', 'read', second, '--source', 'recent')).toContain('CHROME_alive');
    const content = await secondPane.locator('.pane-content').boundingBox();
    let firstContext = true, releaseContext!: () => void;
    const contextGate = new Promise<void>(resolve => { releaseContext = resolve; });
    await page.route('**/api/action', async route => {
      if (route.request().postDataJSON()?.action === 'pane.copy_context' && firstContext) {
        firstContext = false; await contextGate;
        await route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ error: 'pane content changed' }) });
      } else await route.continue();
    });
    await run('Terminal: copy mode (native scrollback)'); await expect(page.locator('#panes > .copy-toolbar')).toBeVisible();
    expect(await secondPane.locator('.pane-content').boundingBox()).toEqual(content);
    await page.locator('.copy-toolbar [data-copy=find]').click(); await page.getByRole('searchbox', { name: 'Search native scrollback' }).fill('CHROME_alive');
    await page.getByRole('searchbox', { name: 'Search native scrollback' }).press('Enter');
    releaseContext();
    await expect(page.locator('.copy-match')).not.toHaveCount(0);
    await page.unroute('**/api/action');
    await page.screenshot({ path: 'test-results/pane-chrome-copy.png' });
    await page.locator('.copy-toolbar [data-copy=exit]').click(); await expect(page.locator('.copy-layer')).toHaveCount(0);
    expect(await original!.evaluate(node => node.isConnected)).toBe(true);
    await page.locator('#settings').click(); await page.locator('#settings-reset').click();
    await expect(secondPane.locator('.pane-title')).toBeVisible();
    await page.locator('#settings-cancel').click(); await expect(secondPane.locator('.pane-title')).toBeHidden();
    await runtime.restartGateway(); await page.reload(); await expect(page.locator('#shield')).toBeHidden();
    await expect(page.locator('#tabs')).toHaveCSS('order', '3');
    await expect(page.locator('.pane-active')).toHaveCSS('border-left-width', '0px');
    await page.locator('.pane-active textarea').focus(); await page.keyboard.type("printf 'RESTORED_%s\\n' \"$CHROME_KEEP\""); await page.keyboard.press('Enter');
    await expect.poll(() => runtime.cli('pane', 'read', second, '--source', 'recent')).toContain('RESTORED_alive');
    await page.screenshot({ path: 'test-results/pane-chrome-desktop.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.locator('#tabs')).toHaveCSS('order', '0');
    await expect(page.locator('.terminal-pane:visible')).toHaveCount(1);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/pane-chrome-mobile.png' });
  } finally { await runtime.close(); }
});
