import { test, expect } from '@playwright/test';
import { fixture } from './fixture';
import { consoleInput } from './console-helpers';
let runtime: Awaited<ReturnType<typeof fixture>>;
test.beforeAll(async () => { runtime = await fixture(); });
test.afterAll(async () => { await runtime?.close(); });
test('theme/font preview preserves the terminal, cancellation restores values, and saved settings survive restart', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(runtime.url); await consoleInput(page, 'token', runtime.token); await expect(page.locator('#boot')).toBeHidden();
  await page.getByRole('button', { name: 'Create workspace', exact: true }).click(); await expect(page.locator('#shield')).toBeHidden();
  const original = await page.locator('#terminal textarea').elementHandle();
  const color = () => page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--herdr-panel-bg').trim());
  const initial = await color();
  await page.locator('#settings').click();
  await page.locator('[data-setting=theme]').selectOption('catppuccin-latte');
  await expect.poll(color).toBe('#eff1f5');
  await page.locator('[data-setting=fontSize]').fill('18');
  await expect(page.locator('#shield')).toBeHidden();
  expect(await original!.evaluate(node => node === document.querySelector('#terminal textarea'))).toBe(true);
  await page.locator('#settings-cancel').click(); await expect.poll(color).toBe(initial);
  await page.locator('#settings').click();
  await page.locator('[data-setting=appearance]').selectOption('system');
  await page.emulateMedia({ colorScheme: 'light' }); await expect.poll(color).toBe('#eff1f5');
  await page.emulateMedia({ colorScheme: 'dark' }); await expect.poll(color).toBe('#181825');
  await page.locator('[data-setting=appearance]').selectOption('theme');
  await page.locator('[data-setting=theme]').selectOption('nord');
  await page.locator('[data-setting=sidebarWidth]').fill('320');
  await page.locator('[data-setting=hideSingleTab]').check();
  await page.locator('#settings-device-font').check();
  await page.locator('#settings-device-size').fill('18');
  await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click();
  await expect(page.locator('#settings-dialog')).toBeHidden(); await expect(page.locator('#tabs')).toBeHidden();
  await expect(page.locator('#rail')).toHaveCSS('width', '320px');
  expect(await page.evaluate(() => localStorage.getItem('werdr-device-font-size'))).toBe('18');
  expect((await (await page.request.get(runtime.url + '/api/settings')).json()).preferences.fontSize).toBe(14);
  const saved = await color();
  await runtime.restartGateway(); await page.reload(); await expect(page.locator('#boot')).toBeHidden(); await expect(page.locator('#shield')).toBeHidden();
  await expect.poll(color).toBe(saved); await expect(page.locator('#rail')).toHaveCSS('width', '320px');
  await page.locator('#terminal textarea').focus(); await page.keyboard.type("printf 'SETTINGS_%s\\n' KEPT_SHELL"); await page.keyboard.press('Enter');
  const pane = JSON.parse(await runtime.cli('api', 'snapshot')).result.snapshot.panes[0].pane_id;
  await expect.poll(() => runtime.cli('pane', 'read', pane, '--source', 'recent')).toContain('SETTINGS_KEPT_SHELL');
  await page.locator('#settings').click(); await expect(page.locator('#settings-dialog')).toBeVisible(); await page.screenshot({ path: 'test-results/settings-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: 'test-results/settings-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
