import { test, expect } from '@playwright/test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fixture } from './fixture';
import { consoleInput } from './console-helpers';

const exec = promisify(execFile);
test('workspace rows consume live cached Git independently of native rows, preview safely and persist across gateway restart', async ({ page }) => {
  test.setTimeout(120000);
  const runtime = await fixture(false, false, false, undefined, process.env.WERDR_WORKSPACE_ROWS_NATIVE_BIN || resolve('../target/release/herdr'));
  try {
    const repo = join(runtime.directory, 'repository'), origin = join(runtime.directory, 'origin.git'); await mkdir(repo);
    const git = (...args: string[]) => exec('git', ['-C', repo, ...args], { env: { ...process.env, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null', GIT_AUTHOR_NAME: 'Fixture', GIT_AUTHOR_EMAIL: 'fixture@example.invalid', GIT_COMMITTER_NAME: 'Fixture', GIT_COMMITTER_EMAIL: 'fixture@example.invalid' } });
    await git('init', '-b', 'main'); await git('commit', '--allow-empty', '-m', 'initial'); await git('init', '--bare', origin);
    await git('remote', 'add', 'origin', origin); await git('push', '-u', 'origin', 'main'); await git('commit', '--allow-empty', '-m', 'ahead');
    const configPath = join(runtime.directory, 'herdr/config.toml'), nativeConfig = '[ui.sidebar.spaces]\nrows = [["workspace"]]\n';
    await mkdir(join(runtime.directory, 'herdr'), { recursive: true }); await writeFile(configPath, nativeConfig);
    await page.goto(runtime.url); await consoleInput(page, 'token', runtime.token); await expect(page.locator('#boot')).toBeHidden();
    const reload = await page.request.post(runtime.url + '/api/action', { headers: { Origin: runtime.url }, data: { machine: 'local', action: 'server.reload_config' } }); expect(reload.ok(), await reload.text()).toBe(true);
    const active = JSON.parse(await runtime.cli('worktree', 'open', '--cwd', repo, '--path', repo, '--label', 'Review checkout')).result.root_pane;
    const row = page.locator(`#workspaces button[data-id="local/${active.workspace_id}"]`);
    await row.click(); await expect(page.locator('#shield')).toBeHidden();
    const terminal = await page.locator('#terminal textarea').elementHandle(), identity = await row.elementHandle();
    await expect(row.locator('[data-token=branch]')).toHaveText('main'); await expect(row.locator('[data-token=git_status]')).toHaveText('↑1');
    await expect(row.locator('.workspace-host')).not.toHaveText('Local');
    await git('commit', '--allow-empty', '-m', 'another ahead');
    await expect(row.locator('[data-token=git_status]')).toHaveText('↑2');
    const upstream = (await git('commit-tree', 'HEAD~2^{tree}', '-p', 'HEAD~2', '-m', 'upstream change')).stdout.trim();
    await git('update-ref', 'refs/remotes/origin/main', upstream);
    await expect(row.locator('[data-token=git_status]')).toHaveText('↑2 ↓1');
    const colors = await row.locator('[data-token=git_status] > span').evaluateAll(parts => parts.map(part => getComputedStyle(part).color));
    expect(colors[0]).not.toBe(colors[2]);
    await expect.poll(() => readFile(configPath, 'utf8')).toBe(nativeConfig);
    await runtime.cli('workspace', 'report-metadata', active.workspace_id, '--source', 'row-test', '--token', 'build=<b>failed</b>', '--seq', '1');
    await page.locator('#settings').click(); await page.locator('#settings-workspace-rows summary').click();
    const editor = page.locator('#settings-workspace-row-config');
    const config = { rows: [['state_icon', 'workspace'], ['branch', { token: 'git_status', fg: '#abc', bold: true, dim: true }], [{ token: '$build', rules: [{ contains: 'failed', fg: '#f44', dim: false }] }]], row_gap: 1 };
    await editor.fill(JSON.stringify(config)); await expect(row.locator('.agent-line')).toHaveCount(3);
    await expect(row.locator('[data-token=custom]')).toHaveText('<b>failed</b>'); await expect(row.locator('b')).toHaveCount(0);
    await expect(row.locator('[data-token=git_status]')).toHaveCSS('color', 'rgb(170, 187, 204)');
    await expect(row.locator('[data-token=git_status]')).toHaveCSS('opacity', '0.7');
    await expect(row.locator('[data-token=custom]')).toHaveCSS('color', 'rgb(255, 68, 68)');
    await editor.fill('{ invalid'); await expect(page.locator('#settings-error')).toContainText('Workspace rows: enter valid JSON');
    await page.locator('#settings-cancel').click(); await expect(row.locator('.agent-line')).toHaveCount(2);
    expect(await terminal!.evaluate(node => node === document.querySelector('#terminal textarea'))).toBe(true);
    expect(await identity!.evaluate(node => node.isConnected)).toBe(true);
    await page.locator('#settings').click(); await page.locator('#settings-workspace-rows summary').click(); await editor.fill(JSON.stringify(config));
    await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click(); await expect(page.locator('#settings-dialog')).toBeHidden();
    const childPath = join(runtime.directory, 'review-child'); await git('worktree', 'add', '-b', 'worktree/review', childPath);
    const child = JSON.parse(await runtime.cli('worktree', 'open', '--cwd', repo, '--path', childPath)).result.root_pane;
    const childRow = page.locator(`#workspaces button[data-id="local/${child.workspace_id}"]`);
    await expect(childRow.locator('[data-token=workspace]')).toHaveText('review');
    await expect(childRow.locator('[data-token=branch], [data-token=git_status]')).toHaveCount(0);
    await expect(childRow.locator('.row-prefix')).toHaveText('└─ ');
    await runtime.cli('workspace', 'rename', child.workspace_id, 'Manual child'); await expect(childRow.locator('[data-token=workspace]')).toHaveText('Manual child');
    const spacing = await row.locator('..').evaluate(node => ({ gap: parseFloat(getComputedStyle(node).marginBottom), line: node.querySelector('.agent-line')!.getBoundingClientRect().height }));
    expect(Math.abs(spacing.gap - spacing.line)).toBeLessThan(1);
    await page.screenshot({ path: 'test-results/workspace-rows-desktop.png' });
    await runtime.restartGateway(); await page.reload(); await expect(page.locator('#shield')).toBeHidden();
    await expect(row.locator('[data-token=custom]')).toHaveText('<b>failed</b>');
    const stored = await (await page.request.get(runtime.url + '/api/settings')).json(); expect(stored.preferences.workspaceRows).toEqual(config);
    await page.locator('#settings').click(); await page.locator('[data-setting=sidebarWidth]').fill('160'); await page.getByRole('button', { name: 'SAVE SETTINGS', exact: true }).click();
    await expect(page.locator('#settings-dialog')).toBeHidden();
    await expect.poll(() => row.locator('.agent-line').evaluateAll(lines => lines.every(line => [...line.querySelectorAll<HTMLElement>('.agent-token:not([hidden])')].every(token => token.getBoundingClientRect().right <= line.getBoundingClientRect().right + 1)))).toBe(true);
    await page.screenshot({ path: 'test-results/workspace-rows-narrow.png' });
    await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#host-toggle').click(); await expect(row).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: 'test-results/workspace-rows-phone.png' });
    const current = await (await page.request.get(runtime.url + '/api/settings')).json();
    const layout = { rows: [[{ token: '$build', rules: [{ contains: 'x'.repeat(16000), fg: '#abc' }] }]], row_gap: 0 };
    const large = { revision: current.revision, preferences: { ...current.preferences, agentRows: { ...layout, rows_by_agent: {} }, workspaceRows: layout, collapsedWorkspaceGroups: Array.from({ length: 4 }, (_, index) => String(index) + 'x'.repeat(8099)) } };
    expect(Buffer.byteLength(JSON.stringify(large))).toBeGreaterThan(65536);
    const saved = await page.request.post(runtime.url + '/api/settings', { headers: { Origin: runtime.url }, data: large }); expect(saved.ok(), await saved.text()).toBe(true);
    const restored = await page.request.post(runtime.url + '/api/settings', { headers: { Origin: runtime.url }, data: { ...current, revision: current.revision + 1 } }); expect(restored.ok(), await restored.text()).toBe(true);
  } finally { await runtime.close(); }
});
