import { test, expect } from '@playwright/test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, writeFile, access } from 'node:fs/promises';
import { join } from 'node:path';
import { fixture } from './fixture';
import { consoleInput } from './console-helpers';
const exec = promisify(execFile);
let runtime: Awaited<ReturnType<typeof fixture>>;
test.beforeAll(async () => { runtime = await fixture(); });
test.afterAll(async () => { await runtime?.close(); });
test('native worktrees create, open, reject dirty removal, and remove only their linked checkout', async ({ page }) => {
  test.setTimeout(90000);
  const repo = join(runtime.directory, 'source'), checkout = join(runtime.directory, 'feature'); await mkdir(repo);
  const git = (...args: string[]) => exec('git', ['-C', repo, ...args], { env: { ...process.env, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null' } });
  await git('init', '-b', 'main'); await writeFile(join(repo, 'README.md'), 'worktree fixture\n'); await git('add', 'README.md'); await git('-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Initial fixture');
  await writeFile(join(repo, '.git', 'hooks', 'post-checkout'), '#!/bin/sh\ncase "$PWD" in */trusted-feature) sleep 11 ;; esac\n: > .hook-ran\n', { mode: 0o700 });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(runtime.url); await consoleInput(page, 'token', runtime.token); await expect(page.locator('#boot')).toBeHidden();
  const open = async () => { await page.locator('#commands').click(); await page.getByRole('button', { name: 'Worktrees: list, create, open or remove', exact: true }).click(); await expect(page.locator('#worktrees-dialog')).toBeVisible(); };
  await open(); await page.locator('#worktree-cwd').fill(repo); await page.getByRole('button', { name: 'LIST WORKTREES', exact: true }).click();
  await expect(page.locator('.worktree-row')).toHaveCount(1); await expect(page.locator('#worktree-repository')).toContainText(repo);
  await page.locator('#worktree-branch').fill('browser-feature'); await page.locator('#worktree-path').fill(checkout); await page.locator('#worktree-label').fill('Browser worktree');
  await page.getByRole('button', { name: 'CREATE AND OPEN', exact: true }).click(); await expect(page.locator('#worktrees-dialog')).toBeHidden(); await expect(page.locator('#shield')).toBeHidden();
  const linkedPane = new URL(page.url()).searchParams.get('pane')!;
  await page.locator('.pane-active textarea').focus(); await page.keyboard.type("printf 'WORKTREE_CWD=%s\\n' \"$PWD\""); await page.keyboard.press('Enter');
  await expect.poll(() => runtime.cli('pane', 'read', linkedPane, '--source', 'recent')).toContain(`WORKTREE_CWD=${checkout}`);
  expect((await exec('git', ['-C', checkout, 'branch', '--show-current'])).stdout.trim()).toBe('browser-feature');
  expect((await git('branch', '--show-current')).stdout.trim()).toBe('main');
  expect(await access(join(checkout, '.hook-ran')).then(() => true, () => false)).toBe(true);
  await expect(page.locator('#workspaces button.active')).toContainText('Browser worktree');
  await open(); await expect(page.locator('.worktree-row')).toHaveCount(2);
  const linked = page.locator('.worktree-row').filter({ has: page.locator('p', { hasText: checkout }) });
  await writeFile(join(checkout, 'dirty.txt'), 'Do not discard by default\n'); await linked.getByRole('button', { name: 'REMOVE', exact: true }).click();
  await page.locator('#worktree-remove-confirm').click(); await expect(page.locator('#worktree-remove-error')).not.toBeEmpty(); await access(join(checkout, 'dirty.txt'));
  await page.locator('#worktree-remove-cancel').click();
  await page.locator('#worktree-done').click();
  const workspace = new URL(page.url()).searchParams.get('workspace')!;
  const closed = await page.request.post(runtime.url + '/api/action', { headers: { Origin: runtime.url }, data: { machine: 'local', action: 'workspace.close', id: workspace } }); expect(closed.ok()).toBe(true);
  await open(); await page.locator('#worktree-cwd').fill(repo); await page.getByRole('button', { name: 'LIST WORKTREES', exact: true }).click(); await expect(linked).toContainText('[CLOSED]');
  await linked.getByRole('button', { name: 'OPEN WORKTREE', exact: true }).click(); await expect(page.locator('#worktrees-dialog')).toBeHidden(); await expect(page.locator('#shield')).toBeHidden();
  await open(); await expect(linked).toContainText('[OPEN]'); await linked.getByRole('button', { name: 'REMOVE', exact: true }).click(); await page.locator('#worktree-force').check(); await page.locator('#worktree-remove-confirm').click();
  await expect(page.locator('#worktree-remove-dialog')).toBeHidden(); await expect(page.locator('.worktree-row')).toHaveCount(1);
  await expect.poll(async () => access(checkout).then(() => true, () => false)).toBe(false); await access(join(repo, 'README.md'));
  await page.screenshot({ path: 'test-results/worktrees-desktop.png' });
  const trusted = join(runtime.directory, 'trusted-feature'); await page.locator('#worktree-branch').fill('trusted-feature'); await page.locator('#worktree-path').fill(trusted); await page.locator('#worktree-trust').check();
  await page.getByRole('button', { name: 'CREATE AND OPEN', exact: true }).click(); await expect(page.locator('#worktrees-dialog')).toBeHidden({ timeout: 30000 }); await access(join(trusted, '.hook-ran'));
  await open(); await expect(page.locator('#worktree-trust')).not.toBeChecked();
  await page.locator('#worktree-cwd').fill(join(runtime.directory, 'missing')); await page.getByRole('button', { name: 'LIST WORKTREES', exact: true }).click(); await expect(page.locator('#worktree-error')).not.toBeEmpty();
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/worktrees-mobile.png' });
  expect(errors).toEqual([]);
});
